### ISSUE TITLE
Additional Items

### ISSUE THREAD

**Issue by ChrisKader** [cr4ckp0t/AdiBags_ZerethMortis#1]
Firim's Spare Forge-tap - [187908](https://wowhead.com/item=187908)
Eidolic Particles - [187789](https://wowhead.com/item=187789)
Trace Enigmet - [187790](https://wowhead.com/item=187790)
Kismetric Circlet - [187791](https://wowhead.com/item=187791)
Lost Ovoid - [190239](https://wowhead.com/item=190239)
Unstable Containment Trap - [187909](https://wowhead.com/item=187909)

**Comment by cr4ckp0t** [comment]
Awesome, thanks! I'll get it added to the next version.

**Comment by cr4ckp0t** [comment]
Added the items in version 1.1.3. Thanks again!
