### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by N6REJ** [cr4ckp0t/AdiBags_ZerethMortis#2]
The latest update broke something... 
![image](https://user-images.githubusercontent.com/1850089/157836540-142e897b-2af4-4447-ac6c-50590f3d8a1f.png)
![image](https://user-images.githubusercontent.com/1850089/157836625-ec207681-735b-4258-b946-9a74f1187fde.png)

According to the .lua your missing the addon file itself..
![image](https://user-images.githubusercontent.com/1850089/157836839-89971fe5-038e-4a0c-8c16-4ddb526f7374.png)

**Comment by N6REJ** [comment]
installing the missing .lua removes the error
![image](https://user-images.githubusercontent.com/1850089/157837130-f1d3421c-745a-4389-a0de-8f38b269626f.png)

**Comment by cr4ckp0t** [comment]
What lua was missing? I'm showing the same thing you posted.

The file shows the same: https://github.com/cr4ckp0t/AdiBags_ZerethMortis/blob/main/AdiBags_ZerethMortis.toc

**Comment by N6REJ** [comment]
https://github.com/cr4ckp0t/AdiBags_ZerethMortis/blob/main/ZerethMortis.lua

**Comment by cr4ckp0t** [comment]
I'm afraid I don't follow what you're saying, so I'm just going to close this.
