### ISSUE TITLE
Protoform Synthesis Lupine Lattice filter not working for me

### ISSUE THREAD

**Issue by reubenrichards** [cr4ckp0t/AdiBags_ZerethMortis#3]
for me Lupine Lattice is still showing up in miscellaneous in bank, reagent and bags. The other protoform synthesis lattices and motes etc are getting correctly filtered into Protoform Synthesis.

Edit:
I am seeing the ID for Lupine Lattice as 190388

**Comment by reubenrichards** [comment]
I made that change in ProtoformSynthesis.lua and fixed it for me. Might just be a cut and paste error, or blizz changed it in an update.

at line 44:
    [190388] = true, -- Lupine Lattice	(RAR - 11 April 2022)

**Comment by cr4ckp0t** [comment]
It was probably just a transcription error on my part. I fixed it in the latest version. Thanks!
